name: Function App Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '6.0.x'
jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: Development 
    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v2
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build "./WebFunctions/WebFunctions.csproj" --configuration Release --output ./output
          popd
